# Use an official Node.js runtime as a parent image
FROM node:22

RUN apt-get update && apt-get install 

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your app runs on (default is 3000 for Node.js)
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]
